# Site settings
title: Duy Phuong Doan
description: Duy Phuong Doan's portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Duy Phuong Doan
user_description: Greetings weary traveller, my name is Phuong, an experienced game developer who has recently dabbled in game design. I am concerned with everything to do with ideas and game development. Should you require assistance, my wisdom is all yours.
user_title: Game Developer
email: doanduyphuong98@gmail.com
github_username:  dphuong98

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
